openapi: "3.0.3"
info:
  title: Shop App (User API)
  version: 0.0.1
  contact:
    name: Mateusz
    url: https://github.com/matgalv2
servers:
  - url: http://localhost:8080
    description: local dev
paths:
  /clients:
    get:
      operationId: getAllClients
      x-jvm-package: clients
      responses:
        200:
          description: Fetches a list of clients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GetClient"
    post:
      operationId: createClient
      x-jvm-package: clients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateClient"
      responses:
        201:
          description: Fetches a client by client id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientId'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /clients/{clientId}:
    get:
      operationId: getClientById
      x-jvm-package: clients
      parameters:
        - in: path
          name: clientId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        200:
          description: Fetches a client by client id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetClient'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      operationId: updateClient
      x-jvm-package: clients
      parameters:
        - in: path
          name: clientId
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateClient"
      responses:
        204:
          description: Updates a client
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      operationId: deleteClient
      x-jvm-package: clients
      parameters:
        - in: path
          name: clientId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        204:
          description: Deletes a client
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  schemas:
    GetClient:
      type: object
      properties:
        clientId:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date
        phone:
          type: string
          pattern: '^\+[0-9]{1,3}-[0-9]{6,}$'
        createdAt:
          type: string
          x-scala-type: java.time.LocalDateTime
      required:
        - clientId
        - firstName
        - lastName
        - phone
        - createdAt

    CreateClient:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date
        phone:
          type: string
          pattern: '^\+[0-9]{1,3}-[0-9]{6,}$'
      required:
        - firstName
        - lastName
        - phone

    UpdateClient:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date
        phone:
          type: string
          pattern: '^\+[0-9]{1,3}-[0-9]{6,}$'
      required:
        - firstName
        - lastName
        - phone

    ClientId:
      type: object
      properties:
        clientId:
          type: string
          format: uuid
      required:
        - clientId

    ErrorResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            type: string
      required:
        - messages